WebApplication4/WebApplication4/Models/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication4.Models
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public DateTime DateAdded { get; set; }
        public DateTime DateModified { get; set; }
        public string Sentence { get; set; }
        public IEnumerable<Keyword> Keywords { get; set; }
    }
}

WebApplication4/WebApplication4/Models/EditProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication4.Models
{
    public class EditProjectViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
    }
}

WebApplication4/WebApplication4/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication4.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }

        [Required(ErrorMessage = "Please enter a project name")]
        [Display(Name = "Project name")]
        public string Name { get; set; }
        public DateTime DateAdded { get; set; }
        public DateTime DateModified { get; set; }
        public string Sentence { get; set; }
        //public virtual ICollection<Keyword> KeywordsSentence { get; set; }

        [ForeignKey("User")]
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

WebApplication4/WebApplication4/Controllers/KeywordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    [Authorize]
    public class KeywordController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ApplicationDbContext context;

        public KeywordController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddKeyword(AddWordsViewModel model)
        {
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == model.ProjectId);
            if (project == null)
            {
                ViewBag.ErrorMessage = $"User with id = {model.ProjectId} cannot be found";
                return View("NOT FOUND");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var word = new Keyword
                    {
                        Word = model.Word,
                        ProjectId = model.ProjectId,
                        Project = project,
                        DateStarted = DateTime.Now,
                        Active = model.Active
                        
                    };
                    project.DateModified = DateTime.Now;

                    context.Projects.Update(project);
                    await context.Keywords.AddAsync(word);
                    await context.SaveChangesAsync();

                    if (word == null)
                        ViewData["word"] = "Word not added successfully!";
                    else if(word!=null)
                        return Redirect("/Project/Details/" + project.ProjectId);
                }

            }
            return View(model);
        }

        public IActionResult DeleteWord(string id)
        {
            int idFromRoute = int.Parse(id);
            var word = context.Keywords.FirstOrDefault(x => x.KeywordId == idFromRoute);
            string projectId = word.ProjectId.ToString();
            if (word == null)
            {
                ViewBag.ErrorMessage = $"Word with id ={id} cannot be found";
                return View("NOT FOUND");
            }
            else
            {
                context.Keywords.Remove(word);
                context.SaveChanges();

                if (context.Keywords.FirstOrDefault(x=>x.KeywordId==word.KeywordId)==null)
                {
                    return Redirect("/Project/Details/"+projectId);
                }

                return RedirectToAction("Index", "Home");
                
            }
        }

        public IActionResult ActivateOrDisable(string id)
        {
            int idFromRoute = int.Parse(id);
            var word = context.Keywords.FirstOrDefault(x => x.KeywordId == idFromRoute);
            string projectId = word.ProjectId.ToString();
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == word.ProjectId);
            if (word == null)
            {
                ViewBag.ErrorMessage = $"Word with id ={id} cannot be found";
                return View("NOT FOUND");
            }
            else
            {
                if(word.Active==true)
                {
                    word.Active = false;
                }
                else if(word.Active==false)
                {
                    word.Active = true;
                }
                project.DateModified = DateTime.Now;

                context.Keywords.Update(word);
                context.Projects.Update(project);
                context.SaveChanges();

                return Redirect("/Project/Details/" + projectId);              


            }
        }

        [HttpGet]
        public IActionResult AddKeyword(string id)
        {
            int idFromRoute = int.Parse(id);
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == idFromRoute);
            if (project == null)
            {
                ViewBag.ErrorMessage = $"Poject with id = {id} cannot be found";
                return View("NOT FOUND");
            }

            AddWordsViewModel model = new AddWordsViewModel { ProjectId = project.ProjectId };

            return View(model);
        }
    }
}

WebApplication4/WebApplication4/Controllers/TweetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    [Authorize]
    public class TweetController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ApplicationDbContext context;

        public TweetController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SerachForTweets(string id)
        {
            int idFromRoute = int.Parse(id);
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == idFromRoute);
            if (project == null)
            {
                ViewBag.ErrorMessage = $"Project with id = {id} cannot be found";
                return View("NOT FOUND");
            }

            IEnumerable<Keyword> keywords = new List<Keyword>();
            if (project != null)
            {
                keywords = context.Keywords.Where(x => x.ProjectId == project.ProjectId);
            }

            double negativeTweets = 0;
            double positiveTweets = 0;
            double neutralTweets = 0;
            double total = 0;
            IEnumerable<Tweet> tweets = new List<Tweet>();
            DateTime[] labels= { };
            double[] indexes= { };
            for (int i = 0; i < keywords.Count(); i++)
            {
                if (keywords.ElementAt(i).Active == true)
                {
                    tweets = context.Tweets.Where(x => x.Value.Contains(keywords.ElementAt(i).Word)).AsEnumerable();
                    labels = new DateTime[tweets.Count()];
                    indexes = new double[tweets.Count()];
                    for (int j = 0; j < tweets.Count(); j++)
                    {
                        labels[j] = tweets.ElementAt(j).Date;
                        indexes[j] = tweets.ElementAt(j).Sentiment;
                        if (tweets.ElementAt(j).Sentiment == 1)
                        {
                            positiveTweets++;
                            total++;
                        }
                        else if (tweets.ElementAt(j).Sentiment == 0)
                        {
                            neutralTweets++;
                            total++;
                        }
                        else if (tweets.ElementAt(j).Sentiment == -1)
                        {
                            negativeTweets++;
                            total++;
                        }
                        Keyword_Tweet connectionTable = new Keyword_Tweet
                        {
                            Keyword = keywords.ElementAt(i),
                            KeywordId = keywords.ElementAt(i).KeywordId,
                            Tweet = tweets.ElementAt(j),
                            TweetId = tweets.ElementAt(j).TweetId,                         
                        };
                        context.Keyword_Tweets.Add(connectionTable);
                        context.SaveChanges();
                    }
                }
            }

            double negativeTweetsPercent = 0;
            double positiveTweetsPercent = 0;
            double neutralTweetsPercent = 0;


            if (negativeTweets > 0)
            {
                negativeTweetsPercent = (negativeTweets / total) * 100;
            }

            if (positiveTweets > 0)
            {
                positiveTweetsPercent = (positiveTweets / total) * 100;
            }

            if (neutralTweets > 0)
            {
                neutralTweetsPercent = (neutralTweets / total) * 100;
            }

           

            var model = new SearchForTweetsModel
            {
                ProjectId = project.ProjectId,
                PositiveTweets = Math.Round(positiveTweetsPercent, 0),
                NeutralTweets = Math.Round(neutralTweetsPercent, 0),
                NegativeTweets = Math.Round(negativeTweetsPercent, 0),
                Sentence = project.Sentence,
                Labels = labels,
                TweetSentiments = indexes
            };

            setOpinion(model);

            return View(model);
        }



        public void setOpinion(SearchForTweetsModel model)
        {
            if (model.PositiveTweets > model.NegativeTweets && model.PositiveTweets > model.NeutralTweets || model.NegativeTweets == model.NeutralTweets)
            {
                model.Opinion = "It seems like your product is on a good way. Many people tweeted positive things about it and we all know how important is their opinion. This product has a very good place when it comes to human pleasures. I think it deserves a star from me. Go search for another one! I hope it will be at least as good as this one.";
            }
            else if (model.NegativeTweets > model.PositiveTweets && model.NegativeTweets > model.NegativeTweets || model.PositiveTweets == model.NeutralTweets)
            {
                model.Opinion = "Meeeh, not such a good choice :(. This product is not well seen in people's eyes. They did not tweet so many good things about it. There are more bad comment than good ones. I hope this will not dissapoint you. Go try for another product! Maybe there will be a better one.";
            }
            else if (model.NeutralTweets > model.NegativeTweets && model.NeutralTweets > model.PositiveTweets || model.PositiveTweets == model.NegativeTweets)
            {
                model.Opinion = "Hmmmm, I don't know what to say. It seems like opinions are divided. Tweets are impartial in this context. Maybe in the future we will have a much more precise view. Go try for another one and for this product I think you should wait a little more in order for the people to decide if it is worth it or not.";
            }
        }

        [HttpGet]
        public IActionResult Back(string id)
        {
            int idFromRoute = int.Parse(id);
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == idFromRoute);

            return Redirect("/Project/Details/"+project.ProjectId);
        }


      
    }
}

WebApplication4/WebApplication4/Views/Project/AddProject.cshtml
@model WebApplication4.Models.CreateProjectViewModel

@{
    ViewData["Title"] = "Add Project";
}

    <div style="padding-left:5%;">
        <h1>Add Project</h1>

        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="AddProject" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*<label asp-for="UserId" class="control-label"></label>*@
                        <input type="hidden" asp-for="UserId" class="form-control" contenteditable="false" />
                    </div>
                    <div class="form-group">
                        <button type="submit" class="submit">Add</button>
                    </div>
                </form>

            </div>
        </div>
        <h4 style="color:red;">@ViewData["notCreated"]</h4>

        <div>
            <a class="submit" asp-route-id="@Model.UserId" asp-controller="Account" asp-action="MyProfile">Back to My Profile</a>
        </div>

    </div>

WebApplication4/WebApplication4/Views/Project/Details.cshtml
@model WebApplication4.Models.DetailsViewModel

@{
    ViewData["Title"] = "Details";
}


    <div style="padding-left:5%;">

        <table style="width:100%">

            <tr>
                <td style="font-weight: bold;">@Html.DisplayFor(model => model.Name)</td>
                <td style="text-align:right;">
                    Date and time added: @Html.DisplayFor(model => model.DateAdded)| Last modified on: @Html.DisplayFor(model => model.DateModified)
                </td>
            </tr>
        </table>
        <br />
        <table class="words" style="width:100%">
            <tr class="rows">
                <th class="header">Word</th>
                <th class="header">Date started</th>
                <th class="header">Action</th>
            </tr>
            @if (Model.Keywords.Count() > 0)
            {

                @foreach (var word in Model.Keywords)
                {
                    <tr class="rows">
                        <td class="columns">
                            @word.Word
                        </td>
                        <td class="columns">
                            @word.DateStarted
                        </td>
                        <td class="columns" style="text-align:right;">
                            <div style="white-space: nowrap;">
                                <input disabled type="checkbox" asp-for="@word.Active">
                                @if (word.Active == true)
                                {
                                    <a asp-action="ActivateOrDisable" asp-controller="Keyword" asp-route-id="@word.KeywordId">Disable</a>
                                }
                                else if (word.Active == false)
                                {
                                    <a asp-action="ActivateOrDisable" asp-controller="Keyword" asp-route-id="@word.KeywordId">Activate</a>
                                }
                                <a asp-action="DeleteWord" asp-controller="Keyword" asp-route-id="@word.KeywordId">Delete</a>

                            </div>
                        </td>
                    </tr>
                }


            }
            else
            {
                <tr class="rows" style="text-align:center;">
                    <td class="columns">-</td>
                    <td class="columns">-</td>
                    <td class="columns">-</td>
                </tr>
            }
        </table>
        <br />
        <div style="text-align:right;">
            <a class="submit" asp-route-id="@Model.Id" asp-controller="Keyword" asp-action="AddKeyword">Add a word</a>
        </div>

        <div class="form-group">
            <label asp-for="Sentence" class="control-label"></label>
            <input disabled="disabled" asp-for="Sentence" class="form-control" />
        </div>
        
        <div style="text-align:right;">
            @if (Model.Sentence != null)
            {
                <a class="submit" asp-route-id="@Model.Id" asp-controller="Tweet" asp-action="SerachForTweets">START</a>
            }
        </div>

    </div>

<link href="~/css/addkeyword.css" rel="stylesheet" />

WebApplication4/WebApplication4/Views/Project/EditProject.cshtml
@model WebApplication4.Models.EditProjectViewModel

@{
    ViewData["Title"] = "EditProject";
}
<div style="padding-left:5%;">
    <h1>Edit Project</h1>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="EditProject">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @*<label asp-for="Id" class="control-label"></label>*@
                    <input type="hidden" disabled asp-for="Id" class="form-control" />
                    @*<span asp-validation-for="Id" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="submit" />
                    <a asp-route-id="@Model.UserId" asp-action="MyProfile" asp-controller="Account" class="submit">Cancel</a>

                </div>
            </form>
        </div>
    </div>


</div>