WebApplication4/WebApplication4/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ApplicationDbContext context;

        public ProjectController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.context = context;
        }

        public IActionResult DeleteProject(string id)
        {
            int idFromRoute = int.Parse(id);
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == idFromRoute);
            string userId = project.UserId;
            if (project == null)
            {
                ViewBag.ErrorMessage = $"Project with id ={id} cannot be found";
                return View("NOT FOUND");
            }
            else
            {
                foreach (var word in context.Keywords.Where(x => x.ProjectId == project.ProjectId))
                {
                    context.Keywords.Remove(word);
                }
                context.Projects.Remove(project);
                context.SaveChanges();

                if (context.Projects.FirstOrDefault(x => x.ProjectId == project.ProjectId) == null)
                {
                    return Redirect("/Account/MyProfile/" + userId);
                }

                return RedirectToAction("Index", "Home");

            }
        }

        [HttpGet]
        public IActionResult EditProject(string id)
        {
            int idFromRoute = int.Parse(id);
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == idFromRoute);
            if (project == null)
            {
                ViewBag.ErrorMessage = $"Project with id = {id} cannot be found";
                return View("NOT FOUND");
            }

            var model = new EditProjectViewModel
            {
                Id = project.ProjectId,
                Name = project.Name,
                UserId = project.UserId
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult EditProject(EditProjectViewModel model)
        {
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == model.Id);
            if (project == null)
            {
                ViewBag.ErrorMessage = $"Project with id = {model.Id.ToString()} cannot be found";
                return View("NOT FOUND");
            }
            else
            {
                project.Name = model.Name;

                context.Projects.Update(project);
                context.SaveChanges();
                if (context.Projects.FirstOrDefault(x => x.ProjectId == model.Id&&x.Name==model.Name)!=null)
                {
                    return Redirect("/Account/MyProfile/"+project.UserId);
                }                
            }

            return View(model);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddProject(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id = {id} cannot be found";
                return View("NOT FOUND");
            }

            CreateProjectViewModel project = new CreateProjectViewModel { UserId = user.Id};

            return View(project);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            int idFromRoute = int.Parse(id);
            var project = context.Projects.FirstOrDefault(x => x.ProjectId == idFromRoute);
            if (project == null)
            {
                ViewBag.ErrorMessage = $"Project with id = {id} cannot be found";
                return View("NOT FOUND");
            }

            var model = new DetailsViewModel
            {
                Id = project.ProjectId,
                Name = project.Name,
                DateAdded=project.DateAdded,
                DateModified=project.DateModified,
            };

            IEnumerable<Keyword> keywords = new List<Keyword>();
            if (model.Id>0)
            {
                keywords = context.Keywords.Where(x => x.ProjectId == model.Id);
            }

            model.Keywords = keywords;

            string sentence = null;
            if (model.Keywords.Count() > 0)
            {            
                for (int i = 0; i < model.Keywords.Count(); i++)
                {
                    if (model.Keywords.ElementAt(i).Active == true)
                    {
                        sentence += model.Keywords.ElementAt(i).Word+" ";
                    }
                }
            }
            model.Sentence = sentence;
            project.Sentence = model.Sentence;
            context.Projects.Update(project);
            context.SaveChanges();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddProject(CreateProjectViewModel model)
        {
         
            var user = await userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id = {model.UserId} cannot be found";
                return View("NOT FOUND");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var project = new Project
                    {
                        Name = model.Name,
                        UserId = model.UserId,
                        User = user,
                        DateAdded = DateTime.Now,
                        DateModified = DateTime.Now
                    };

                    await context.Projects.AddAsync(project);
                    await context.SaveChangesAsync();

                    if (project == null)
                        ViewData["notCreated"] = "Project not created successfully!";
                    else if (project != null)
                        return Redirect("/Project/Details/" + project.ProjectId);
                }                    
                  
            }
            return View(model);
        }
    }
}

WebApplication4/WebApplication4/Views/Shared/_Favicon.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <link rel="icon" type="image/png" href="~/logo/icon.png" sizes="50x50" />

WebApplication4/WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SentimentPredator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @Html.Partial("_Favicon")
    @using Microsoft.AspNetCore.Identity
    @inject SignInManager<ApplicationUser> SignInManager
    @inject UserManager<ApplicationUser> UserManager

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img alt="Brand" src="~/logo/logoo.png" height="60" width="250" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>*@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="MyProfile" asp-controller="Account" asp-route-id="@UserManager.GetUserId(Context.User)">My projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="AddProject" asp-controller="Project" asp-route-id="@UserManager.GetUserId(Context.User)">Add project</a>
                            </li>
                        }
                        @*else
                        {
                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                        }*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin:0%;border:none;padding:0px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:white;">
        <div class="container">
            &copy; 2020 - SentimentPredator|
            Phone number: 0725511358|
            Email: d007608@gmail.com|
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>